gutter:
  include: true
  theme:
    leslietheme: true
menu:
  theme:
    leslietheme: true
grid:
  theme:
    leslietheme: true
lightbox:
  include: true
base:
  desk-wide-start: 1020px
card:
  include: false
segment:
  include: false
